### ISSUE TITLE
ObjectMapper crashes due to nil values

### ISSUE THREAD

**Issue by mitchellporter** [mattwyskiel/GoogleAPISwiftClient#1]
Hey Matt,

First off great job on starting this library. I've been having nothing but trouble with some of the legacy google API libraries and couldn't believe they still had ARC disabled.

Anyways, I went to go use this to upload a video to youtube and I was having trouble. I tried creating a `YoutubeVideo` object and I needed to add a `YoutubeVideoSnippet` to it, and all I need to set on the snippet are the `title` and `description` keys. I quickly realized that leaving any of these key values nil results in a crash.

Is there a reason for this, or am I misunderstanding?

**Comment by mattwyskiel** [comment]
Hi Mitchell,

Thanks for filing the issue. Sorry for the delay.

I made a simple sample project on my personal computer to try to replicate what you were doing, and I found that there was a bug in my code for one of my custom JSON-to-Object transformers (as you may have guessed, it does not handle a nil value like it is supposed to). It is now fixed locally, and I will push an update very soon (I am currently working on improving error handling and instantiation of objects as well).

I will post a comment here when the update is indeed pushed up to CocoaPods etc.

**Comment by mitchellporter** [comment]
Thanks for the response :)

This is a great library. I ended up using an objc alternative, but I'll keep an eye on this. Not sure how long you've been working with Swift but the code structure was very clean.

Cheers.

**Comment by mattwyskiel** [comment]
I just pushed up version 0.4.1 of the library to CocoaPods. It fixes the specific issue you brought up regarding nil key values and it improves error reporting of requests and instantiation of model objects.

However, in regards to the general situation you describe of uploading a YouTube video, I realize that my library doesn't yet support media uploads. That'll be my next task!

Anyways, thanks for letting me know about the issue! It really helps a lot.
